---
name: fish-actions/syntax-check

description: Syntax check all fish files in your repository

branding:
  icon: check-circle
  color: blue

runs:
  using: composite

  steps:
    - run: |
        set -l numFails 0

        for file in $GITHUB_WORKSPACE/**.fish
            fish --no-execute $file || set numFails (math $numFails + 1)
        end

        exit $numFails
      shell: fish {0}
